### PR TITLE
Fixed: Option to run single instance of bot for all users

### PR DESCRIPTION
**Pull request by klisfer**

### CODE REVIEW

**Comment by Drymonade** [comment]
@klisfer To reminder bot: Messages are mixed up, I received remindings from my colleague.

**Comment by Drymonade** [comment]
@klisfer And to mention-tracker: it is working fine, but there are small issue about time: 
Снимок экрана 2019-05-29 в 14 13 19
Can you fix it and filter them up that it was only mention from the last week?

**Comment by klisfer** [comment]
@Drymonade Are you sure about the reminder bot? Because as far as the code goes it cannot only set reminder for the peer.id which has invoked the message or event. Check if you updated the code, and if the issue still persists replicate the result and send me all the logs , i have just added a few logs and made a commit to the repo.
and for the date parts with mention bot , that returns the wrong date because that's what the bot returns the date to be. Here is a screenshot of the log of the callback from the dialog bot instance.
Screenshot 2019-05-29 at 6 35 27 PM

**Comment by Drymonade** [comment]
@klisfer
Снимок экрана 2019-05-29 в 18 55 13

```
PEER1 Peer { id: 1023096535, type: 'private', strId: null }
PEER1 Peer { id: 713921617, type: 'private', strId: null }
I've started, post me something @Reminder
USER User {
  name: 'Andrey Skiba',
  peer: Peer { id: 1023096535, type: 'private', strId: null } }
USER User {
  name: 'Mikhail Fomichev',
  peer: Peer { id: 713921617, type: 'private', strId: null } }
UUID {
  msb: Long { low: -2111303191, high: -391310799, unsigned: false },
  lsb: Long { low: 2014814543, high: -774978848, unsigned: false } }
UUID {
  msb: Long { low: -2111303191, high: -391310800, unsigned: false },
  lsb: Long { low: 898864585, high: -1921441076, unsigned: false } }
UUID {
  msb: Long { low: -2111303191, high: -328370800, unsigned: false },
  lsb: Long { low: -182408519, high: -1558312143, unsigned: false } }
PEER Peer { id: 713921617, type: 'private', strId: null }
UUID {
  msb: Long { low: -2111303191, high: -303160800, unsigned: false },
  lsb: Long { low: 1241818430, high: -1153075156, unsigned: false } }
PEER Peer { id: 713921617, type: 'private', strId: null }
UUID {
  msb: Long { low: -2111303191, high: -242540800, unsigned: false },
  lsb: Long { low: 410318936, high: 1771640654, unsigned: false } }
PEER Peer { id: 713921617, type: 'private', strId: null }
UUID {
  msb: Long { low: -2111303191, high: -237590800, unsigned: false },
  lsb: Long { low: -556547334, high: 318700739, unsigned: false } }
PEER Peer { id: 1023096535, type: 'private', strId: null }
UUID {
  msb: Long { low: -2111303191, high: -221610800, unsigned: false },
  lsb: Long { low: 1951519955, high: -979156448, unsigned: false } }
PEER Peer { id: 1023096535, type: 'private', strId: null }
PEER Peer { id: 1023096535, type: 'private', strId: null }
UUID {
  msb: Long { low: -2111303191, high: -153010800, unsigned: false },
  lsb: Long { low: 728795136, high: 328329073, unsigned: false } }
UUID {
  msb: Long { low: -2111237655, high: 362509200, unsigned: false },
  lsb: Long { low: -844297163, high: 1414350956, unsigned: false } }
UUID {
  msb:
   Long { low: -2111237655, high: -2047798096, unsigned: false },
  lsb:
   Long { low: -1534025709, high: -1523154377, unsigned: false } }
```

**Comment by klisfer** [comment]
@Drymonade In both the instances you haven't even selected a time , the hour: min field is empty you need to select at button. The task stated that there needs to be buttons to give certain pre defined time frames and an option to select custom time. Since you did not specify any time the bot didn't get any peer to send the reminder to so it sent the reminder to all the active users

**Comment by klisfer** [comment]
Screenshot 2019-05-30 at 12 27 42 AM
Screenshot 2019-05-30 at 12 27 52 AM

These are two different instances of the same bot as you can see in the screenshots both ran at the same time with different reminders.

**Comment by klisfer** [comment]
@Drymonade And let's please get over the testrail bounty by the end of the day , otherwise it will get pushed to next friday by bountysource.

**Comment by Drymonade** [comment]
@klisfer We've selected time via "Specify time" in example below, it's just wrong control refreshing when changing chats. This case takes place when two people use bot _simultaneously_, this is difficult to check by one person. 
Feedback on test rail will be returned today.

**Comment by klisfer** [comment]
@Drymonade I checked in two different windows logged in as 2 different users , one with username @robin and another one @bat_man (refer screenshots). Moreover as you can see in my screenshots , when you choose a time from specify time , it shows in the place holders the exact selected time , which is not shown in your screenshot. Kindly run the test with multiple users once again and send me the logs and steps taken in the process along with screenshot.

**Comment by klisfer** [comment]
@Drymonade I have added another set of logs to the code, kindly run the test with multiple users and send me the logs with screenshots and mention the steps taken by you in the process.

**Comment by klisfer** [comment]
@Drymonade Okay , I think I found the issue . I forgot to pass the value of peer where the custom reminder was being scheduled that is the reason it got sent to all the active users. I fixed it , kindly test it again, I should work perfectly fine.

**Comment by Drymonade** [comment]
@klisfer Yes, it's OK, thanks a lot!

**Pull request merged**
